//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int ID_zakaz { get; set; }
        public string numberzakaz { get; set; }
        public Nullable<int> blin_ID { get; set; }
        public Nullable<int> employee_ID { get; set; }
    
        public virtual blini blini { get; set; }
        public virtual employee employee { get; set; }
    }
}
